filePathCSV = "./indicadores.csv"
filePathDates = "./dates.bin"
filePathWeights = "./weights.bin"
filePathMeasurements = "./measurements.npz"
fileMeta = "./meta.npz"
fileSettings = "./settings.json"
prefix = "/api"
